# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
#    app.example:
#        class: AppBundle\Service\ExampleService
#        arguments: ["@doctrine.orm.entity_manager"]
