version: "2"

services:
  nginx.symfony:
    container_name: nginx.symfony
    image: aurelijusb/docker:nginx-latest
    volumes:
      - ../:/code # Mount your code, so nginx/phpcould see it
    ports:
      - 127.0.0.1:8000:80 # For development. Open in browser 127.0.0.1:8000

  php.symfony:
    container_name: php.symfony
    image: aurelijusb/docker:php-latest
    volumes:
      - ../:/code # Mount your code, so nginx/phpcould see it

  mysql.symfony:
    container_name: mysql.symfony
    image: aurelijusb/docker:mysql-latest
    volumes:
      - ../.docker/mysql-data/:/var/lib/mysql # To persist data between restarts
    ports:
      - 127.0.0.1:3307:3306 # Connect to it via -h127.0.0.1 --port=3307